import { useEffect, useState, type FormEvent } from 'react';
import { Activity, Archive, Bell, BookOpen, CalendarDays, Check, ChevronDown, ClipboardCheck, Clock3, FileEdit, FileText, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Stethoscope, Users, X } from 'lucide-react';
import { createPathwayDraft, createUserAccount, decideApproval, getApprovalQueue, getCurrentProfile, getDashboardData, getPathway, listDepartments, listNotifications, listPathways, listUsers, markNotificationRead, signIn, signOut, submitPathway, updateUserProfile, type AppRole, type ApprovalDecision } from './lib/api';
import { isSupabaseConfigured, supabase } from './lib/supabase';
import ExistingPathwayEditor from './ExistingPathwayEditor';
import PathwayHistoryComments from './PathwayHistoryComments';

type Page = 'dashboard'|'library'|'authoring'|'approval'|'users'|'settings';
type UserProfile = { full_name:string; role:AppRole };
type Pathway = { id?:string; title:string; code:string; department:string; status:'Active'|'Draft'|'Review'|'Archived'; version:string; updated:string; author:string; progress:number };
const pathways:Pathway[] = [
  {title:'Acute Ischemic Stroke',code:'CP-NEU-001',department:'Neurology',status:'Active',version:'v3.2',updated:'2 jam lalu',author:'dr. Maya Putri',progress:100},
  {title:'Community Acquired Pneumonia',code:'CP-PUL-008',department:'Pulmonology',status:'Review',version:'v2.0',updated:'Kemarin',author:'dr. Arif Rahman',progress:78},
  {title:'Type 2 Diabetes Mellitus',code:'CP-INT-014',department:'Internal Medicine',status:'Active',version:'v4.1',updated:'3 hari lalu',author:'dr. Sinta Dewi',progress:100},
  {title:'Uncomplicated Appendicitis',code:'CP-SUR-006',department:'General Surgery',status:'Draft',version:'v1.3',updated:'5 hari lalu',author:'dr. Bima Aditya',progress:45},
  {title:'Normal Vaginal Delivery',code:'CP-OBG-003',department:'Obstetrics',status:'Archived',version:'v2.4',updated:'12 Jun 2026',author:'dr. Nisa Ramadi',progress:100},
];

const nav = [{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'library',label:'Pathway Library',icon:BookOpen},{id:'authoring',label:'Authoring',icon:FileEdit},{id:'approval',label:'Approval Queue',icon:ClipboardCheck,badge:'4'}] as const;

export default function App(){
 const [page,setPage]=useState<Page>('dashboard'); const [mobile,setMobile]=useState(false); const [logged,setLogged]=useState(!isSupabaseConfigured); const [authLoading,setAuthLoading]=useState(isSupabaseConfigured); const [selected,setSelected]=useState<Pathway|null>(null); const [profile,setProfile]=useState<UserProfile|null>(isSupabaseConfigured?null:{full_name:'Admin System',role:'administrator'}); const [notifications,setNotifications]=useState<any[]>([]); const [showNotifications,setShowNotifications]=useState(false);
 useEffect(()=>{if(!isSupabaseConfigured)return;const load=async(session:boolean)=>{setLogged(session);if(session){try{setProfile(await getCurrentProfile())}catch{setProfile(null)}}else setProfile(null);setAuthLoading(false)};supabase.auth.getSession().then(({data})=>void load(Boolean(data.session)));const {data}=supabase.auth.onAuthStateChange((_event,session)=>void load(Boolean(session)));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(logged&&isSupabaseConfigured)listNotifications().then(setNotifications).catch(()=>setNotifications([]))},[logged]);
 if(authLoading) return <div className="app-loading"><Activity className="spin"/><span>Menyiapkan CliniPath...</span></div>;
 if(!logged) return <Login onLogin={async(email,password)=>{await signIn(email,password);setLogged(true)}}/>;
 const role=profile?.role||'viewer'; const canAuthor=role==='administrator'||role==='author'; const canApprove=role==='administrator'||role==='reviewer'||role==='approver'; const isAdmin=role==='administrator'; const displayName=profile?.full_name||'Pengguna'; const initials=displayName.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
 const go=(p:Page)=>{setPage(p);setMobile(false);setSelected(null)};
 return <div className="app">
  <aside className={`sidebar ${mobile?'open':''}`}>
   <div className="brand"><div className="brandmark"><Stethoscope size={23}/></div><div><b>CliniPath</b><span>Medical Pathway</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
   <div className="hospital"><div className="hospital-icon">RS</div><div><strong>RS Sehat Sentosa</strong><span>Jakarta Pusat</span></div><ChevronDown size={15}/></div>
   <p className="nav-title">WORKSPACE</p><nav>{nav.filter(n=>n.id!=='authoring'||canAuthor).filter(n=>n.id!=='approval'||canApprove).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><n.icon size={19}/><span>{n.label}</span></button>)}</nav>
   {isAdmin&&<><p className="nav-title">MANAGEMENT</p><nav><button className={page==='users'?'active':''} onClick={()=>go('users')}><Users size={19}/><span>Users & Roles</span></button><button className={page==='settings'?'active':''} onClick={()=>go('settings')}><Settings size={19}/><span>Settings</span></button></nav></>}
   <div className="user"><div className="avatar">{initials}</div><div><strong>{displayName}</strong><span>{roleLabel(role)}</span></div><button onClick={async()=>{if(isSupabaseConfigured)await signOut();setLogged(false)}} title="Keluar"><LogOut size={17}/></button></div>
  </aside>
  {mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">Clinic Pathway <span>/</span> <b>{selected?selected.title:page[0].toUpperCase()+page.slice(1)}</b></div><div className="header-actions"><button className="iconbtn"><Search size={20}/></button><button className="iconbtn notification" onClick={()=>setShowNotifications(!showNotifications)}><Bell size={20}/>{notifications.length>0&&<i/>}</button><div className="top-avatar">{initials}</div>{showNotifications&&<div className="notification-panel"><div><b>Notifikasi</b><span>{notifications.length} belum dibaca</span></div>{notifications.length===0?<p>Tidak ada notifikasi baru.</p>:notifications.map(n=><button key={n.id} onClick={async()=>{await markNotificationRead(n.id);setNotifications(x=>x.filter(y=>y.id!==n.id));setShowNotifications(false);if(n.pathway_id)go('library')}}><strong>{n.title}</strong><span>{n.message}</span></button>)}</div>}</div></header>
   {selected?<DetailLive item={selected} back={()=>setSelected(null)} canEdit={canAuthor}/>:page==='dashboard'?<DashboardLive go={go} canAuthor={canAuthor}/>:page==='library'?<LibraryLive select={setSelected} go={go} canAuthor={canAuthor}/>:page==='authoring'&&canAuthor?<Authoring onCreated={()=>go('library')}/>:page==='approval'&&canApprove?<Approval role={role}/>:page==='users'&&isAdmin?<UsersPage/>:<Placeholder page={page}/>} 
  </main>
 </div>
}

function Login({onLogin}:{onLogin:(email:string,password:string)=>Promise<void>}){
 const [email,setEmail]=useState('admin@clinipath.local'); const [password,setPassword]=useState('Admin123!'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{await onLogin(email,password)}catch(err){setError(err instanceof Error?err.message:'Login gagal')}finally{setLoading(false)}};
 return <div className="login"><section><div className="brand loginbrand"><div className="brandmark"><Stethoscope/></div><div><b>CliniPath</b><span>Medical Pathway</span></div></div><div className="login-copy"><span className="eyebrow">CLINICAL EXCELLENCE</span><h1>Better pathways.<br/>Better outcomes.</h1><p>Platform terintegrasi untuk menyusun, meninjau, dan menerapkan clinical pathway berbasis bukti.</p><div className="login-stat"><b>128</b><span>Active Pathways</span><b>18</b><span>Medical Departments</span></div></div></section><form onSubmit={submit}><span className="eyebrow">SELAMAT DATANG</span><h2>Masuk ke akun Anda</h2><p>Gunakan akun rumah sakit yang telah terdaftar.</p>{error&&<div className="login-error">{error}</div>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="formrow"><label className="remember"><input type="checkbox" defaultChecked/> Ingat saya</label><a>Lupa password?</a></div><button className="primary wide" disabled={loading}>{loading?'Memproses...':'Masuk ke CliniPath'}</button><small>Protected by enterprise-grade security</small></form></div>
}

function Dashboard({go}:{go:(p:Page)=>void}){return <div className="content"><div className="pagehead"><div><span className="date"><CalendarDays size={15}/> Selasa, 7 Juli 2026</span><h1>Selamat pagi, Admin</h1><p>Berikut ringkasan aktivitas clinical pathway hari ini.</p></div><button className="primary" onClick={()=>go('authoring')}><Plus size={18}/> Buat Pathway</button></div><div className="stats"><Stat label="Total Pathway" value="156" delta="+12 tahun ini" icon={FileText}/><Stat label="Pathway Aktif" value="128" delta="82% dari total" icon={Check}/><Stat label="Menunggu Review" value="14" delta="4 perlu tindakan" icon={Clock3}/><Stat label="Akan Kedaluwarsa" value="6" delta="Dalam 30 hari" icon={Archive}/></div><div className="grid-main"><section className="panel activity-panel"><div className="panelhead"><div><h3>Aktivitas Pathway</h3><p>Jumlah pathway dibuat dan dipublikasikan</p></div><select><option>6 bulan terakhir</option></select></div><div className="chart"><div className="yaxis"><span>30</span><span>20</span><span>10</span><span>0</span></div>{[42,58,49,72,64,86].map((v,i)=><div className="barcol" key={i}><div className="bars"><i style={{height:v+'%'}}/><b style={{height:(v-22)+'%'}}/></div><span>{['Feb','Mar','Apr','Mei','Jun','Jul'][i]}</span></div>)}</div><div className="legend"><i/> Dibuat <i/> Dipublikasikan</div></section><section className="panel status-panel"><div className="panelhead"><div><h3>Status Pathway</h3><p>Distribusi saat ini</p></div><MoreHorizontal/></div><div className="donut"><div><b>156</b><span>Total</span></div></div><div className="status-list"><span><i className="green"/>Aktif <b>128</b></span><span><i className="orange"/>Review <b>14</b></span><span><i className="blue"/>Draft <b>8</b></span><span><i className="gray"/>Arsip <b>6</b></span></div></section></div><section className="panel recent"><div className="panelhead"><div><h3>Baru Diperbarui</h3><p>Perubahan terakhir pada clinical pathway</p></div><button className="link" onClick={()=>go('library')}>Lihat semua →</button></div><PathTable items={pathways.slice(0,4)}/></section></div>}

function Stat({label,value,delta,icon:Icon}:{label:string,value:string,delta:string,icon:any}){return <div className="stat"><div className="stat-icon"><Icon size={21}/></div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div>}
function Badge({status}:{status:Pathway['status']}){return <span className={'badge '+status.toLowerCase()}><i/>{status}</span>}
function PathTable({items,onSelect}:{items:Pathway[],onSelect?:(p:Pathway)=>void}){return <div className="tablewrap"><table><thead><tr><th>CLINICAL PATHWAY</th><th>DEPARTEMEN</th><th>STATUS</th><th>VERSI</th><th>DIPERBARUI</th><th></th></tr></thead><tbody>{items.map(p=><tr key={p.code} onClick={()=>onSelect?.(p)}><td><div className="docicon"><FileText size={18}/></div><div><b>{p.title}</b><span>{p.code}</span></div></td><td>{p.department}</td><td><Badge status={p.status}/></td><td><b>{p.version}</b></td><td>{p.updated}</td><td><MoreHorizontal size={18}/></td></tr>)}</tbody></table></div>}

function Library({select}:{select:(p:Pathway)=>void}){const [q,setQ]=useState('');const [filter,setFilter]=useState('All');const [items,setItems]=useState<Pathway[]>(pathways);const [loading,setLoading]=useState(isSupabaseConfigured);const [error,setError]=useState('');useEffect(()=>{if(!isSupabaseConfigured)return;listPathways().then(rows=>setItems(rows.map((r:any)=>({title:r.title,code:r.code,department:r.departments?.name||'-',status:dbStatus(r.status),version:`v${r.current_version}.0`,updated:new Date(r.updated_at).toLocaleDateString('id-ID'),author:r.profiles?.full_name||'-',progress:r.status==='published'?100:50})))).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const shown=items.filter(p=>(filter==='All'||p.status===filter)&&p.title.toLowerCase().includes(q.toLowerCase()));return <div className="content"><div className="pagehead"><div><h1>Pathway Library</h1><p>Temukan dan kelola seluruh clinical pathway rumah sakit.</p></div><button className="primary"><Plus size={18}/> Buat Pathway</button></div><div className="tabs">{['All','Active','Draft','Review','Archived'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}<span>{x==='All'?items.length:items.filter(p=>p.status===x).length}</span></button>)}</div><section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Cari nama atau kode pathway..." value={q} onChange={e=>setQ(e.target.value)}/></div><select><option>Semua departemen</option></select><select><option>Terakhir diperbarui</option></select></div>{loading?<DataState text="Memuat pathway..."/>:error?<DataState text={error} error/>:<PathTable items={shown} onSelect={select}/>}<div className="pagination"><span>Menampilkan 1–{shown.length} dari {shown.length} pathway</span><div><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></div></section></div>}

function Detail({item,back}:{item:Pathway,back:()=>void}){return <div className="content"><button className="back" onClick={back}>← Kembali ke Library</button><div className="detailhead"><div className="detailicon"><FileText/></div><div><div><Badge status={item.status}/><span className="code">{item.code}</span></div><h1>{item.title}</h1><p>{item.department} • Disusun oleh {item.author} • {item.version}</p></div><button className="secondary">Unduh PDF</button><button className="primary">Edit Pathway</button></div><div className="detailgrid"><section className="panel detailbody"><div className="sectionblock"><span className="eyebrow">OVERVIEW</span><h3>Tujuan Klinis</h3><p>Memberikan tata laksana terstandar berbasis bukti untuk meningkatkan keselamatan pasien, konsistensi pelayanan, serta efisiensi penggunaan sumber daya rumah sakit.</p></div><div className="sectionblock"><h3>Kriteria Inklusi</h3><ul><li>Pasien dewasa usia ≥18 tahun</li><li>Diagnosis terkonfirmasi berdasarkan pemeriksaan klinis dan penunjang</li><li>Onset gejala sesuai dengan protokol pelayanan</li></ul></div><div className="sectionblock"><h3>Alur Perawatan</h3>{['Asesmen awal dan stabilisasi pasien','Pemeriksaan diagnostik dan laboratorium','Intervensi medis sesuai indikasi','Monitoring, evaluasi, dan perencanaan pulang'].map((x,i)=><div className="step"><b>{i+1}</b><div><strong>{x}</strong><span>Target penyelesaian dan indikator klinis tercantum dalam protokol.</span></div></div>)}</div></section><aside className="detailaside"><section className="panel"><h3>Informasi Dokumen</h3><Info l="Status" v={item.status}/><Info l="Versi" v={item.version}/><Info l="Pemilik" v={item.author}/><Info l="Diperbarui" v={item.updated}/><Info l="Review berikutnya" v="7 Januari 2027"/></section><section className="panel"><h3>Progres Implementasi</h3><div className="progress"><i style={{width:item.progress+'%'}}/></div><b>{item.progress}%</b> unit telah mengimplementasikan pathway ini.</section></aside></div></div>}
function Info({l,v}:{l:string,v:string}){return <div className="info"><span>{l}</span><b>{v}</b></div>}

function Authoring({onCreated}:{onCreated:()=>void}){
 const [departments,setDepartments]=useState<{id:string;code:string;name:string}[]>([]); const [title,setTitle]=useState(''); const [code,setCode]=useState(''); const [department,setDepartment]=useState(''); const [diagnosis,setDiagnosis]=useState(''); const [icd,setIcd]=useState(''); const [summary,setSummary]=useState(''); const [objective,setObjective]=useState(''); const [steps,setSteps]=useState([{title:'Asesmen & Diagnosis',description:''},{title:'Intervensi / Terapi',description:''},{title:'Monitoring & Evaluasi',description:''}]); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{listDepartments().then(data=>{setDepartments(data);if(data[0])setDepartment(data[0].id)}).catch(e=>setError(e.message))},[]);
 const save=async(review:boolean)=>{setError('');if(!title.trim()||!code.trim()||!department){setError('Nama, kode, dan departemen wajib diisi.');return}setSaving(true);try{const id=await createPathwayDraft({title,code,department_id:department,diagnosis_name:diagnosis,icd10_code:icd,summary,clinical_objective:objective,steps:steps.map((s,i)=>({...s,position:i+1}))});if(review)await submitPathway(id);onCreated()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan pathway')}finally{setSaving(false)}};
 const complete=[title,code,department,diagnosis,icd,summary,objective,steps.some(s=>s.description)].filter(Boolean).length; const percent=Math.round(complete/8*100);
 return <div className="content"><div className="pagehead"><div><h1>Buat Clinical Pathway</h1><p>Lengkapi informasi klinis dan susun alur pelayanan.</p></div><div><button className="secondary" disabled={saving} onClick={()=>save(false)}>Simpan Draft</button> <button className="primary" disabled={saving} onClick={()=>save(true)}>{saving?'Menyimpan...':'Kirim untuk Review'}</button></div></div>{error&&<div className="login-error">{error}</div>}<div className="author-grid"><section className="panel form"><h3>Informasi Dasar</h3><div className="two"><label>Nama Clinical Pathway<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Contoh: Acute Ischemic Stroke"/></label><label>Kode Pathway<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="CP-DEP-001"/></label></div><div className="two"><label>Departemen<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Pilih departemen</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Diagnosis<input value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} placeholder="Nama diagnosis"/></label></div><div className="two"><label>Kode ICD-10<input value={icd} onChange={e=>setIcd(e.target.value.toUpperCase())} placeholder="Contoh: I63.9"/></label><label>Tujuan Klinis<input value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Target utama pelayanan"/></label></div><label>Ringkasan Klinis<textarea value={summary} onChange={e=>setSummary(e.target.value)} rows={4} placeholder="Jelaskan tujuan dan ruang lingkup clinical pathway..."/></label><h3>Alur Pelayanan</h3>{steps.map((step,i)=><div className="editor" key={i}><div><b>{i+1}</b><input className="step-title" value={step.title} onChange={e=>setSteps(steps.map((s,j)=>j===i?{...s,title:e.target.value}:s))}/>{steps.length>1&&<button className="remove-step" onClick={()=>setSteps(steps.filter((_,j)=>j!==i))}><X size={15}/></button>}</div><textarea value={step.description} onChange={e=>setSteps(steps.map((s,j)=>j===i?{...s,description:e.target.value}:s))} rows={3} placeholder="Tuliskan tindakan, target, dan indikator klinis..."/></div>)}<button className="addstep" onClick={()=>setSteps([...steps,{title:'Tahapan Baru',description:''}])}><Plus size={17}/> Tambah Tahapan</button></section><aside className="panel checklist"><h3>Kelengkapan Dokumen</h3>{[['Informasi dasar',Boolean(title&&code&&department)],['Diagnosis & ICD',Boolean(diagnosis&&icd)],['Alur pelayanan',steps.some(s=>Boolean(s.description))],['Tujuan klinis',Boolean(objective)],['Ringkasan',Boolean(summary)]].map(([label,done],i)=><div key={String(label)}><span className={done?'done':''}>{done?<Check size={14}/>:i+1}</span>{label}</div>)}<div className="completion"><span><b>{percent}%</b> lengkap</span><div><i style={{width:percent+'%'}}/></div></div></aside></div></div>
}

type ApprovalItem = { id:string; stage:'review'|'final_approval'; title:string; code:string; department:string; version:string; author:string; objective:string; criteria:string[]; steps:{position:number;title:string;description:string}[] };
function Approval({role}:{role:AppRole}){
 const [items,setItems]=useState<ApprovalItem[]>([]); const [selected,setSelected]=useState<ApprovalItem|null>(null); const [notes,setNotes]=useState(''); const [loading,setLoading]=useState(isSupabaseConfigured); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
 const load=async()=>{if(!isSupabaseConfigured){setLoading(false);return}setLoading(true);setError('');try{const rows=await getApprovalQueue(role);setItems(rows.map((r:any)=>({id:r.id,stage:r.stage,title:r.clinical_pathways.title,code:r.clinical_pathways.code,department:r.clinical_pathways.departments?.name||'-',version:`v${r.pathway_versions.version_number}.0`,author:r.clinical_pathways.profiles?.full_name||'-',objective:r.pathway_versions.clinical_objective||'-',criteria:r.pathway_versions.inclusion_criteria||[],steps:(r.pathway_versions.pathway_steps||[]).sort((a:any,b:any)=>a.position-b.position)})))}catch(e){setError(e instanceof Error?e.message:'Gagal memuat antrean')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const decide=async(decision:ApprovalDecision)=>{if((decision==='rejected'||decision==='revision_requested')&&notes.trim().length<3){setError('Catatan wajib diisi untuk penolakan atau permintaan revisi.');return}if(!selected)return;setSaving(true);setError('');try{await decideApproval(selected.id,decision,notes);setSuccess(decision==='approved'?(selected.stage==='review'?'Review disetujui dan diteruskan kepada approver.':'Pathway disetujui dan dipublikasikan.'):'Keputusan berhasil dikirim kepada author.');setSelected(null);setNotes('');await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan keputusan')}finally{setSaving(false)}};
 const expectedStage=role==='approver'?'final_approval':'review';
 return <div className="content"><div className="pagehead"><div><h1>Approval Queue</h1><p>{role==='approver'?'Lakukan persetujuan final sebelum pathway dipublikasikan.':'Tinjau isi klinis pathway sebelum diteruskan ke approver.'}</p></div></div>{success&&<div className="success"><Check size={17}/>{success}</div>}{error&&<div className="login-error">{error}</div>}{loading?<DataState text="Memuat antrean approval..."/>:items.length===0?<DataState text="Tidak ada pathway yang menunggu keputusan Anda."/>:<div className="approval-layout"><div className="reviewcards">{items.map(p=><section className={`panel review ${selected?.id===p.id?'selected-review':''}`} key={p.id}><div className="reviewtop"><div className="docicon"><ClipboardCheck/></div><span className="stage-badge">{p.stage==='review'?'Review Klinis':'Persetujuan Final'}</span></div><h3>{p.title}</h3><p>{p.code} • {p.department}</p><div className="reviewmeta"><span>Diajukan oleh <b>{p.author}</b></span><span>Versi <b>{p.version}</b></span></div>{role!=='administrator'&&p.stage!==expectedStage?<div className="role-warning">Tahap ini tidak sesuai dengan role Anda.</div>:<div className="reviewactions"><button className="primary" onClick={()=>{setSelected(p);setError('');setSuccess('')}}><FileText size={17}/> Tinjau Dokumen</button></div>}</section>)}</div>{selected&&<aside className="panel decision-panel"><div className="decision-head"><div><span className="eyebrow">{selected.stage==='review'?'REVIEW KLINIS':'PERSETUJUAN FINAL'}</span><h2>{selected.title}</h2><p>{selected.code} • {selected.department} • {selected.version}</p></div><button className="iconbtn" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="decision-content"><h3>Tujuan Klinis</h3><p>{selected.objective}</p>{selected.criteria.length>0&&<><h3>Kriteria Inklusi</h3><ul>{selected.criteria.map(x=><li key={x}>{x}</li>)}</ul></>}<h3>Alur Pelayanan</h3>{selected.steps.map(s=><div className="decision-step" key={s.position}><b>{s.position}</b><div><strong>{s.title}</strong><p>{s.description||'Belum ada deskripsi.'}</p></div></div>)}<label>Catatan keputusan<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Wajib untuk penolakan atau permintaan revisi..."/></label></div><div className="decision-actions"><button className="danger" disabled={saving} onClick={()=>decide('rejected')}>Tolak</button><button className="warning" disabled={saving} onClick={()=>decide('revision_requested')}>Minta Revisi</button><button className="primary" disabled={saving} onClick={()=>decide('approved')}><Check size={17}/>{selected.stage==='review'?'Setujui Review':'Setujui & Publikasikan'}</button></div></aside>}</div>}</div>
}
function dbStatus(status:string):Pathway['status']{return status==='published'?'Active':status==='draft'||status==='revision'?'Draft':status==='archived'?'Archived':'Review'}
function roleLabel(role:AppRole){return ({administrator:'Administrator',author:'Author',reviewer:'Reviewer',approver:'Approver',viewer:'Viewer'})[role]}
function DataState({text,error=false}:{text:string,error?:boolean}){return <div className={'data-state '+(error?'error':'')}><Activity className={error?'':'spin'} size={22}/><span>{text}</span></div>}
function Placeholder({page}:{page:Page}){return <div className="content"><div className="pagehead"><div><h1>{page==='users'?'Users & Roles':'Settings'}</h1><p>Kelola konfigurasi dan akses aplikasi.</p></div></div><section className="panel empty"><ShieldCheck size={48}/><h3>Modul siap dikembangkan</h3><p>Halaman ini berada di luar cakupan utama MVP saat ini.</p></section></div>}

type ManagedUser={id:string;full_name:string;email:string|null;employee_id:string|null;role:AppRole;is_active:boolean;department_id:string|null;departments:{name:string}|null};
function UsersPage(){
 const roles:AppRole[]=['administrator','author','reviewer','approver','viewer']; const [users,setUsers]=useState<ManagedUser[]>([]); const [departments,setDepartments]=useState<{id:string;name:string;code:string}[]>([]); const [showForm,setShowForm]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [form,setForm]=useState({full_name:'',email:'',password:'',role:'viewer' as AppRole,department_id:'',employee_id:''});
 const load=async()=>{setLoading(true);setError('');try{const [userRows,departmentRows]=await Promise.all([listUsers(),listDepartments()]);setUsers(userRows as any);setDepartments(departmentRows)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat pengguna')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{await createUserAccount(form);setSuccess(`Akun ${form.email} berhasil dibuat.`);setForm({full_name:'',email:'',password:'',role:'viewer',department_id:'',employee_id:''});setShowForm(false);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal membuat akun')}finally{setSaving(false)}};
 const update=async(user:ManagedUser,changes:Partial<Pick<ManagedUser,'role'|'department_id'|'is_active'>>)=>{const next={role:changes.role??user.role,department_id:changes.department_id===undefined?user.department_id:changes.department_id,is_active:changes.is_active??user.is_active};setError('');try{await updateUserProfile(user.id,next);setUsers(rows=>rows.map(x=>x.id===user.id?{...x,...next}:x));setSuccess(`Akses ${user.full_name} berhasil diperbarui.`)}catch(e){setError(e instanceof Error?e.message:'Gagal memperbarui pengguna')}};
 return <div className="content"><div className="pagehead"><div><h1>Users & Roles</h1><p>Kelola akun, role, departemen, dan status akses pengguna.</p></div><button className="primary" onClick={()=>setShowForm(!showForm)}><Plus size={18}/>{showForm?'Tutup Form':'Buat Akun'}</button></div>{error&&<div className="login-error">{error}</div>}{success&&<div className="success"><Check size={17}/>{success}</div>}{showForm&&<form className="panel user-create" onSubmit={create}><div className="panelhead"><div><h3>Akun Baru</h3><p>Password awal dapat diganti pengguna setelah login.</p></div></div><div className="user-form-grid"><label>Nama lengkap<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password awal<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label>Nomor pegawai<input value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as AppRole})}>{roles.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</select></label><label>Departemen<select value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Tanpa departemen</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="form-submit"><button className="primary" disabled={saving}>{saving?'Membuat akun...':'Simpan Akun'}</button></div></form>}<section className="panel users-panel">{loading?<DataState text="Memuat pengguna..."/>:<div className="tablewrap"><table className="users-table"><thead><tr><th>PENGGUNA</th><th>ROLE</th><th>DEPARTEMEN</th><th>STATUS</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><div className="avatar small-avatar">{user.full_name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><b>{user.full_name}</b><span>{user.email||'Email belum tersedia'}{user.employee_id?` • ${user.employee_id}`:''}</span></div></td><td><select value={user.role} onChange={e=>update(user,{role:e.target.value as AppRole})}>{roles.map(x=><option key={x} value={x}>{roleLabel(x)}</option>)}</select></td><td><select value={user.department_id||''} onChange={e=>update(user,{department_id:e.target.value||null})}><option value="">Tanpa departemen</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><button className={`status-toggle ${user.is_active?'on':'off'}`} onClick={()=>update(user,{is_active:!user.is_active})}>{user.is_active?'Aktif':'Nonaktif'}</button></td></tr>)}</tbody></table></div>}</section></div>
}

function mapPathway(r:any):Pathway{return {id:r.id,title:r.title,code:r.code,department:r.departments?.name||'-',status:dbStatus(r.status),version:`v${r.current_version}.0`,updated:new Date(r.updated_at).toLocaleDateString('id-ID'),author:r.profiles?.full_name||'-',progress:r.status==='published'?100:50}}
function DashboardLive({go,canAuthor}:{go:(p:Page)=>void;canAuthor:boolean}){
 const [data,setData]=useState<{rows:any[];total:number;published:number;pending:number;dueSoon:number}|null>(null); const [error,setError]=useState('');
 useEffect(()=>{if(!isSupabaseConfigured){setData({rows:pathways,total:pathways.length,published:pathways.filter(x=>x.status==='Active').length,pending:pathways.filter(x=>x.status==='Review').length,dueSoon:0});return}getDashboardData().then(setData).catch(e=>setError(e.message))},[]);
 if(error)return <div className="content"><DataState text={error} error/></div>; if(!data)return <div className="content"><DataState text="Memuat dashboard..."/></div>;
 const recent=isSupabaseConfigured?data.rows.slice(0,4).map(mapPathway):pathways.slice(0,4);
 return <div className="content"><div className="pagehead"><div><span className="date"><CalendarDays size={15}/>{new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><h1>Dashboard CliniPath</h1><p>Ringkasan data clinical pathway terbaru.</p></div>{canAuthor&&<button className="primary" onClick={()=>go('authoring')}><Plus size={18}/> Buat Pathway</button>}</div><div className="stats"><Stat label="Total Pathway" value={String(data.total)} delta="Seluruh dokumen" icon={FileText}/><Stat label="Pathway Aktif" value={String(data.published)} delta="Sudah dipublikasikan" icon={Check}/><Stat label="Menunggu Persetujuan" value={String(data.pending)} delta="Review dan approval final" icon={Clock3}/><Stat label="Akan Ditinjau" value={String(data.dueSoon)} delta="Dalam 30 hari" icon={Archive}/></div><section className="panel recent"><div className="panelhead"><div><h3>Baru Diperbarui</h3><p>Perubahan terakhir pada clinical pathway</p></div><button className="link" onClick={()=>go('library')}>Lihat semua →</button></div><PathTable items={recent}/></section></div>
}
function LibraryLive({select,go,canAuthor}:{select:(p:Pathway)=>void;go:(p:Page)=>void;canAuthor:boolean}){
 const [q,setQ]=useState(''); const [filter,setFilter]=useState('All'); const [department,setDepartment]=useState('All'); const [sort,setSort]=useState('latest'); const [items,setItems]=useState<Pathway[]>(isSupabaseConfigured?[]:pathways); const [loading,setLoading]=useState(isSupabaseConfigured); const [error,setError]=useState('');
 useEffect(()=>{if(!isSupabaseConfigured)return;listPathways().then(rows=>setItems(rows.map(mapPathway))).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const departments=[...new Set(items.map(x=>x.department))].sort(); const shown=items.filter(p=>(filter==='All'||p.status===filter)&&(department==='All'||p.department===department)&&(p.title+' '+p.code).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):0);
 return <div className="content"><div className="pagehead"><div><h1>Pathway Library</h1><p>Temukan dan kelola seluruh clinical pathway rumah sakit.</p></div>{canAuthor&&<button className="primary" onClick={()=>go('authoring')}><Plus size={18}/> Buat Pathway</button>}</div><div className="tabs">{['All','Active','Draft','Review','Archived'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}<span>{x==='All'?items.length:items.filter(p=>p.status===x).length}</span></button>)}</div><section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Cari nama atau kode pathway..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="All">Semua departemen</option>{departments.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="latest">Terakhir diperbarui</option><option value="title">Urutkan judul</option></select></div>{loading?<DataState text="Memuat pathway..."/>:error?<DataState text={error} error/>:<PathTable items={shown} onSelect={select}/>}<div className="pagination"><span>Menampilkan {shown.length} dari {items.length} pathway</span></div></section></div>
}
function DetailLive({item,back,canEdit}:{item:Pathway;back:()=>void;canEdit:boolean}){
 const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(Boolean(item.id&&isSupabaseConfigured)); const [error,setError]=useState('');
 const [submitting,setSubmitting]=useState(false); const [actionError,setActionError]=useState(''); const [success,setSuccess]=useState('');
 const [editing,setEditing]=useState(false);
 useEffect(()=>{if(!item.id||!isSupabaseConfigured)return;getPathway(item.id).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[item.id]);
 const sendReview=async()=>{if(!item.id)return;setSubmitting(true);setActionError('');try{await submitPathway(item.id);setSuccess('Pathway berhasil dikirim untuk review.');setTimeout(back,900)}catch(e){setActionError(e instanceof Error?e.message:'Gagal mengirim pathway untuk review')}finally{setSubmitting(false)}};
 if(loading)return <div className="content"><DataState text="Memuat detail pathway..."/></div>; if(error)return <div className="content"><button className="back" onClick={back}>← Kembali</button><DataState text={error} error/></div>;
 const version=data?.pathway_versions?.find((v:any)=>v.version_number===data.current_version)||data?.pathway_versions?.[0]; const steps=(version?.pathway_steps||[]).sort((a:any,b:any)=>a.position-b.position); const objective=version?.clinical_objective||'Belum ada tujuan klinis.'; const criteria=version?.inclusion_criteria||[];
 if(editing&&data)return <ExistingPathwayEditor data={data} version={version} back={()=>setEditing(false)} saved={()=>{setEditing(false);setSuccess('Perubahan draft berhasil disimpan.');if(item.id)getPathway(item.id).then(setData)}}/>;
 return <div className="content"><button className="back" onClick={back}>← Kembali ke Library</button>{actionError&&<div className="login-error">{actionError}</div>}{success&&<div className="success"><Check size={17}/>{success}</div>}<div className="detailhead"><div className="detailicon"><FileText/></div><div><div><Badge status={item.status}/><span className="code">{item.code}</span></div><h1>{item.title}</h1><p>{item.department} • Disusun oleh {item.author} • {item.version}</p></div>{canEdit&&item.status==='Draft'&&<><button className="secondary" onClick={()=>setEditing(true)}><FileEdit size={17}/> Edit Pathway</button><button className="primary" disabled={submitting} onClick={sendReview}><Check size={17}/>{submitting?'Mengirim...':'Kirim untuk Review'}</button></>}</div><div className="detailgrid"><section className="panel detailbody"><div className="sectionblock"><span className="eyebrow">OVERVIEW</span><h3>Tujuan Klinis</h3><p>{objective}</p></div>{criteria.length>0&&<div className="sectionblock"><h3>Kriteria Inklusi</h3><ul>{criteria.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}<div className="sectionblock"><h3>Alur Perawatan</h3>{steps.length?steps.map((s:any)=><div className="step" key={s.id||s.position}><b>{s.position}</b><div><strong>{s.title}</strong><span>{s.description||'Belum ada deskripsi.'}</span></div></div>):<p>Belum ada tahapan pelayanan.</p>}</div></section><aside className="detailaside"><section className="panel"><h3>Informasi Dokumen</h3><Info l="Status" v={item.status}/><Info l="Versi" v={item.version}/><Info l="Pemilik" v={item.author}/><Info l="Diperbarui" v={item.updated}/></section></aside></div>{data&&<PathwayHistoryComments data={data} onRefresh={async()=>{if(item.id)setData(await getPathway(item.id))}}/>}</div>
}
