import { useEffect, useState, type FormEvent } from 'react';
import { Check, Plus, X } from 'lucide-react';
import { listDepartments, updatePathwayDraft } from './lib/api';

export default function ExistingPathwayEditor({data,version,back,saved}:{data:any;version:any;back:()=>void;saved:()=>void}){
 const [departments,setDepartments]=useState<{id:string;name:string}[]>([]); const [title,setTitle]=useState(data.title||''); const [code,setCode]=useState(data.code||''); const [department,setDepartment]=useState(data.department_id||''); const [diagnosis,setDiagnosis]=useState(data.diagnosis_name||''); const [icd,setIcd]=useState(data.icd10_code||''); const [summary,setSummary]=useState(data.summary||''); const [objective,setObjective]=useState(version?.clinical_objective||''); const [criteria,setCriteria]=useState((version?.inclusion_criteria||[]).join('\n')); const [steps,setSteps]=useState((version?.pathway_steps||[]).sort((a:any,b:any)=>a.position-b.position).map((s:any)=>({title:s.title,description:s.description||''}))); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{listDepartments().then(setDepartments).catch(e=>setError(e.message))},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!title.trim()||!code.trim()||!department){setError('Nama, kode, dan departemen wajib diisi.');return}setSaving(true);setError('');try{await updatePathwayDraft(data.id,{title,code,department_id:department,diagnosis_name:diagnosis,icd10_code:icd,summary,clinical_objective:objective,inclusion_criteria:criteria.split('\n').map((x:string)=>x.trim()).filter(Boolean),steps:steps.map((s:any,i:number)=>({...s,position:i+1}))});saved()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan perubahan')}finally{setSaving(false)}};
 return <div className="content"><button className="back" type="button" onClick={back}>← Batal dan kembali</button><form onSubmit={submit}><div className="pagehead"><div><h1>Edit Clinical Pathway</h1><p>Perbarui draft atau tanggapi catatan revisi sebelum dikirim ulang.</p></div><button className="primary" disabled={saving}><Check size={17}/>{saving?'Menyimpan...':'Simpan Perubahan'}</button></div>{error&&<div className="login-error">{error}</div>}<section className="panel form"><h3>Informasi Dasar</h3><div className="two"><label>Nama Clinical Pathway<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Kode Pathway<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label></div><div className="two"><label>Departemen<select value={department} onChange={e=>setDepartment(e.target.value)} required>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Diagnosis<input value={diagnosis} onChange={e=>setDiagnosis(e.target.value)}/></label></div><div className="two"><label>Kode ICD-10<input value={icd} onChange={e=>setIcd(e.target.value.toUpperCase())}/></label><label>Tujuan Klinis<input value={objective} onChange={e=>setObjective(e.target.value)}/></label></div><label>Ringkasan Klinis<textarea rows={4} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label>Kriteria Inklusi <small>(satu kriteria per baris)</small><textarea rows={4} value={criteria} onChange={e=>setCriteria(e.target.value)}/></label><h3>Alur Pelayanan</h3>{steps.map((step:any,i:number)=><div className="editor" key={i}><div><b>{i+1}</b><input className="step-title" value={step.title} onChange={e=>setSteps(steps.map((s:any,j:number)=>j===i?{...s,title:e.target.value}:s))}/>{steps.length>1&&<button type="button" className="remove-step" onClick={()=>setSteps(steps.filter((_:any,j:number)=>j!==i))}><X size={15}/></button>}</div><textarea rows={3} value={step.description} onChange={e=>setSteps(steps.map((s:any,j:number)=>j===i?{...s,description:e.target.value}:s))}/></div>)}<button type="button" className="addstep" onClick={()=>setSteps([...steps,{title:'Tahapan Baru',description:''}])}><Plus size={17}/> Tambah Tahapan</button></section></form></div>
}
