import { useState, type FormEvent } from 'react';
import { Check, Clock3, MessageSquare, Send } from 'lucide-react';
import { addPathwayComment } from './lib/api';

export default function PathwayHistoryComments({data,onRefresh}:{data:any;onRefresh:()=>Promise<void>}){
 const versions=[...(data.pathway_versions||[])].sort((a:any,b:any)=>b.version_number-a.version_number); const comments=[...(data.comments||[])].sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()); const current=versions.find((v:any)=>v.version_number===data.current_version); const [body,setBody]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();if(body.trim().length<2){setError('Komentar minimal 2 karakter.');return}setSaving(true);setError('');setSuccess('');try{await addPathwayComment(data.id,current?.id,body);setBody('');setSuccess('Komentar berhasil ditambahkan.');await onRefresh()}catch(e){setError(e instanceof Error?e.message:'Gagal menambahkan komentar')}finally{setSaving(false)}};
 return <div className="history-comments"><section className="panel history-panel"><div className="panelhead"><div><h3><Clock3 size={16}/> Riwayat Versi</h3><p>Jejak versi clinical pathway.</p></div></div>{versions.length===0?<p className="panel-note">Belum ada versi.</p>:versions.map((v:any)=><div className="history-item" key={v.id}><span className="history-dot"/><div><strong>Versi {v.version_number}.0 {v.version_number===data.current_version&&<i>Aktif</i>}</strong><p>{v.change_summary||'Versi dokumen clinical pathway.'}</p><small>{new Date(v.created_at).toLocaleString('id-ID')}</small></div></div>)}</section><section className="panel comments-panel"><div className="panelhead"><div><h3><MessageSquare size={16}/> Komentar Klinis</h3><p>Diskusi dan catatan terkait dokumen.</p></div></div>{error&&<div className="login-error">{error}</div>}{success&&<div className="success"><Check size={15}/>{success}</div>}<form onSubmit={submit}><textarea rows={3} value={body} onChange={e=>setBody(e.target.value)} placeholder="Tambahkan komentar atau catatan klinis..."/><button className="primary" disabled={saving}><Send size={15}/>{saving?'Mengirim...':'Kirim Komentar'}</button></form><div className="comment-list">{comments.length===0?<p className="panel-note">Belum ada komentar.</p>:comments.map((c:any)=><article key={c.id}><div className="comment-avatar">{(c.profiles?.full_name||'?').split(/\s+/).map((x:string)=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><strong>{c.profiles?.full_name||'Pengguna'}</strong><small>{new Date(c.created_at).toLocaleString('id-ID')}</small><p>{c.body}</p></div></article>)}</div></section></div>
}
